export const initialExecutives = [
  {
    id: 1,
    organizerName: "جهاد دانشگاهی",
    firstName: "حسین",
    lastName: "ولیسه رضایی",
    nationalCode: "1234567890",
    phoneNumber: "09123456789",
    domain: "تهران",
    activityType: "آزمون گر",
    status: "در انتظار",
    hozeAzmoon: "مدرسه علامه حلی - تهران",
    performanceRating: "1",
  },
  {
    id: 2,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "مریم",
    lastName: "احمدی",
    nationalCode: "0987654321",
    phoneNumber: "09354321098",
    domain: "اصفهان",
    activityType: "آزمون گر",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دبیرستان فرهیختگان - اصفهان",
    performanceRating: "3",
  },
  {
    id: 3,
    organizerName: "شرکت آزمون گستر",
    firstName: "رضا",
    lastName: "محمدی",
    nationalCode: "1122334455",
    phoneNumber: "09217654321",
    domain: "فارس",
    activityType: "آزمون گر",
    status: "پایان اجرا",
    hozeAzmoon: "دانشگاه شیراز - ساختمان علوم",
    performanceRating: "4",
  },
  {
    id: 4,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "زهرا",
    lastName: "کریمی",
    nationalCode: "5566778899",
    phoneNumber: "09198765432",
    domain: "خراسان رضوی",
    activityType: "آزمون بان",
    status: "خروج از قرنطینه",
    hozeAzmoon: "مدرسه نمونه امام رضا - مشهد",
    performanceRating: "3",
  },
  {
    id: 5,
    organizerName: "جهاد دانشگاهی",
    firstName: "علی",
    lastName: "رضوی",
    nationalCode: "9876543210",
    phoneNumber: "09129876543",
    domain: "آذربایجان شرقی",
    activityType: "آزمون بان",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دانشگاه تبریز - دانشکده فنی",
    performanceRating: "2",
  },
  {
    id: 6,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "سارا",
    lastName: "محسن‌زاده",
    nationalCode: "4567891234",
    phoneNumber: "09361234567",
    domain: "البرز",
    activityType: "آزمون گر",
    status: "پایان اجرا",
    hozeAzmoon: "دانشگاه آزاد اسلامی واحد کرج",
    performanceRating: "3",
  },
  {
    id: 7,
    organizerName: "شرکت آزمون گستر",
    firstName: "محمد",
    lastName: "اکبری",
    nationalCode: "3216549870",
    phoneNumber: "09219876543",
    domain: "قم",
    activityType: "آزمون بان",
    status: "در انتظار",
    hozeAzmoon: "دبیرستان مهدی موعود - قم",
    performanceRating: "3",
  },
  {
    id: 8,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "فاطمه",
    lastName: "حسینی",
    nationalCode: "6543217890",
    phoneNumber: "09127654321",
    domain: "خوزستان",
    activityType: "آزمون گر",
    status: "خروج از قرنطینه",
    hozeAzmoon: "دانشگاه شهید چمران اهواز",
    performanceRating: "1",
  },
  {
    id: 9,
    organizerName: "جهاد دانشگاهی",
    firstName: "امیر",
    lastName: "قاسمی",
    nationalCode: "7894561230",
    phoneNumber: "09123459876",
    domain: "گیلان",
    activityType: "آزمون بان",
    status: "پایان اجرا",
    hozeAzmoon: "مدرسه البرز - رشت",
    performanceRating: "3",
  },
  {
    id: 10,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "نرگس",
    lastName: "علوی",
    nationalCode: "1472583690",
    phoneNumber: "09359876543",
    domain: "یزد",
    activityType: "مخزن دار",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دانشگاه یزد - دانشکده علوم انسانی",
    performanceRating: "4",
  },
  {
    id: 11,
    organizerName: "شرکت آزمون گستر",
    firstName: "حسن",
    lastName: "کاظمی",
    nationalCode: "2583691470",
    phoneNumber: "09213456789",
    domain: "اصفهان",
    activityType: "مسئول تکثیر",
    status: "پایان اجرا",
    hozeAzmoon: "دانشگاه کاشان - سالن همایش",
    performanceRating: "3",
  },
  {
    id: 12,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "مهسا",
    lastName: "شریفی",
    nationalCode: "3691472580",
    phoneNumber: "09128765432",
    domain: "مرکزی",
    activityType: "مدیر حوزه",
    status: "خروج از قرنطینه",
    hozeAzmoon: "مدرسه استعدادهای درخشان - اراک",
    performanceRating: "2",
  },
  {
    id: 13,
    organizerName: "جهاد دانشگاهی",
    firstName: "بهرام",
    lastName: "نعمتی",
    nationalCode: "7418529630",
    phoneNumber: "09124567890",
    domain: "زنجان",
    activityType: "مسئول تکثیر",
    status: "خروج از قرنطینه",
    hozeAzmoon: "دانشگاه زنجان - دانشکده علوم",
    performanceRating: "3",
  },
  {
    id: 14,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "الهام",
    lastName: "رستمی",
    nationalCode: "8529637410",
    phoneNumber: "09357654321",
    domain: "همدان",
    activityType: "مدیر حوزه",
    status: "خروج از قرنطینه",
    hozeAzmoon: "دانشگاه بوعلی‌سینا - همدان",
    performanceRating: "1",
  },
  {
    id: 15,
    organizerName: "شرکت آزمون گستر",
    firstName: "کاظم",
    lastName: "مرادی",
    nationalCode: "9637418520",
    phoneNumber: "09218765432",
    domain: "کرمان",
    activityType: "مسئول تکثیر",
    status: "در انتظار",
    hozeAzmoon: "دانشگاه شهید باهنر کرمان",
    performanceRating: "4",
  },
  {
    id: 16,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "شیما",
    lastName: "جعفری",
    nationalCode: "1597534862",
    phoneNumber: "09129875432",
    domain: "بوشهر",
    activityType: "مخزن دار",
    status: "در انتظار",
    hozeAzmoon: "دبیرستان نمونه ولایت - بوشهر",
    performanceRating: "3",
  },
  {
    id: 17,
    organizerName: "جهاد دانشگاهی",
    firstName: "پیمان",
    lastName: "اکرمی",
    nationalCode: "3579514862",
    phoneNumber: "09123459876",
    domain: "مازندران",
    activityType: "آزمون بان",
    status: "در انتظار",
    hozeAzmoon: "دانشگاه مازندران - ساری",
    performanceRating: "3",
  },
  {
    id: 18,
    organizerName: "مرکز آموزشی و پژوهشی رایانگان",
    firstName: "لیلا",
    lastName: "زارعی",
    nationalCode: "7531594862",
    phoneNumber: "09358765432",
    domain: "قزوین",
    activityType: "آزمون گر",
    status: "در انتظار",
    hozeAzmoon: "دانشگاه بین‌المللی امام خمینی - قزوین",
    performanceRating: "2",
  },
  {
    id: 19,
    organizerName: "شرکت آزمون گستر",
    firstName: "یاسر",
    lastName: "بهشتی",
    nationalCode: "9513574862",
    phoneNumber: "09217654321",
    domain:"تهران",
    activityType: "مخزن دار",
    status: "ورود به قرنطینه",
    hozeAzmoon: "دبیرستان اندیشه نو - تهران",
    performanceRating: "3",
  },
  {
    id: 20,
    organizerName: "سازمان سنجش و آموزش کشور",
    firstName: "نسیم",
    lastName: "موسوی",
    nationalCode: "1593574862",
    phoneNumber: "09129876543",
    domain: "گلستان",
    activityType: "آزمون گر",
    status: "در انتظار",
    hozeAzmoon: "دانشگاه علوم کشاورزی و منابع طبیعی گرگان",
    performanceRating: "2",
  },
];
